export const Vocabulary = {
  login: "Login",
  userName: "Utilizator",
  password: "Parola",
  resetPassword: "Resetare Parolă",
  requireRegister: "Solicită Înregistrare",
  legalPerson: "Persoană juridică",
  naturalPerson: "Persoană fizică",
  selectAccountType: "Selectează tipul contului:",
  medic: "Medic veterinar",
  student: "Student veterinar",
  assistant: "Tehnician Veterinar/Asistent veterinar",
  owner: "Fermieri/Proprietari de animale de companie",
  accountType: "Cont",
  selectRole: "Selectează rolul utilizatorului:",
  fullName: "Nume și prenume ",
  lastName: "Nume",
  firstName: "Prenume",
  username: "Nume utilizator",
  email: "Email",
  phone: "Telefon",
  requiredField: "Acest câmp este obligatoriu",
  companyName: "Denumirea companiei",
  cuiValidation:
    "Trebuie să conțină un număr de identificare, între 1 și 9 cifre",
  CUI: "CUI",
  registerNo: "Nr. înregistrare",
  representativeName: "Nume și prenume administrator",
  emailValidation: "Introduceți  o adresa valida",
  next: "Următorul pas",
  back: "Pasul anterior",
  country: "Țara",
  county: "Județ",
  city: "Oraș",
  address: "Adresa",
  validationNo: "Număr atestat valid medic veterinar",
  studentCard: "Carnet de student vizat pe anul în curs:",
  qualificationDiploma: "Diplomă de calificare:",
  petOwnerCode: "Cod exploatație / Serie carnet de sănătate animal",
  loadFile: "Incărcare fișier (.jpg/.pdf/.png)",
  currency: "lei",
  month: "lună",
  months: " luni",
  subscription: "Abonamentul",
  subscriptionText:
    "Veți beneficia de o perioadă de free trial de 7 zile. După finalizarea perioadei contravaloarea abonamentului va fi retrasă din contul dumneavoastră. ",
  registerRequest: "Solicită Cont Nou",
  registerForm: "Formular de înregistrare",
  unavailableUserName: "Acest nume de utilizator nu este disponibil",
  uploadFile: "Încărcați fișierul",
  selectSubscriptions: "Selectează abonamentul",
  settings: "Setări",
  logout: "Deconectare",
  demands: "Solicitări",
  users: "Utilizatori",
  categories: "Categorii",
  articles: "Articole",
  attributes: "Atribute",
  tags: "Etichete",
  dashboard: "Dashboard",
  requestsList: "Solicitări cont",
  view: "Vizualizare",
  edit: "Editează",
  noResultsFound: "Nu a fost găsit nici un rezultat",
  request: "Solicitare",
  close: "Închide",
  newUser: "Utilizator nou",
  save: "Salvare",
  passwordConfirmation: "Confirmare parolă",
  classes: "Clase",
  subjects: "Materii",
  courses: "Cursuri",
  grades: "Note",
  notFound: "Pagina nu este disponibilă.",
  filters: "Filtre",
  resetFilter: "Șterge filtre",
  activeUsers: "Utilizatori activi",
  deletedUsers: "Utilizatori inactivi",
  startDate: "Dată început",
  endDate: "Dată finalizare",
  getUserError: "Eroare la găsirea utilizatorului!",
  addUserSuccess: "Utilzator adăugat cu succes!",
  updateUserSuccess: "Utilizator actualizat cu succes!",
  addNewSubject: "Adaugă materie",
  subject: "Materie",
  name: "Denumire",
  credits: "Credite",
  minValue: "Numărul minim de credite este 1.",
  maxValue: "Numărul maxim de credite este 10.",
  isMandatory: "Materie obligatorie",
  generalAddSuccess: "Datele au fost adăugate cu succes!",
  generalAddError: "Adăugarea datelor a eșuat!",
  generalUpdateSuccess: "Datele au fost actualizate cu succes!",
  generalUpdateError: "Actualizarea datelor a eșuat!",
  generalDeleteSuccess: "Datele au fost șterse cu succes!",
  generalDeleteError: "Ștergerea datelor a eșuat!",
  addClass: "Adaugă clasă",
};
